### ISSUE TITLE
Add publiccode.yml with meta data

### ISSUE THREAD

**Issue by darkdragon-001** [it-at-m/digiwf-core#998]
Please add a [`publiccode.yml`](https://github.com/publiccodeyml/publiccode.yml#readme) to make the project more easily discoverable.

**Comment by xdoo** [comment]
@FabianWilms do we have a suitable publiccode.yml?

**Comment by FabianWilms** [comment]
Sadly we do not have any publiccode.yml at hand. We started to create a version for COVe but stopped as the project was not continued.

The creation process is actually fairly easy using an editor like https://publiccode-editor.developers.italia.it/

**Comment by xdoo** [comment]
https://publiccode-editor.developers.italia.it/ is a very frustrating tool. I invested nearly a hour to fill everything out (no chance to save, because there are always required fields left). If you add english as language, everything has gone. 

Second try with a minimal version (only required fields):
![image](https://user-images.githubusercontent.com/712911/158761526-e7051449-c85f-45b0-8704-50f23c8c327f.png)

I'll keep this issue open, but will put no more effort in it.

**Comment by darkdragon-001** [comment]
I don't know what you are doing, but it worked for me out of the box. I don't know the project well enough to fill in the right values everywhere. Here is the result from my trial:

```yaml
# This repository adheres to the publiccode.yml standard by including this 
# metadata file that makes public software easily discoverable.
# More info at https://github.com/italia/publiccode.yml

publiccodeYmlVersion: '0.2'
categories:
  - it-management
description:
  it:
    features:
      - automation
    genericName: Automation Platform
    longDescription: |
      Back in 2019 we startet to use the great [Camunda](https://camunda.com/)
      BPMN engine as embedded service inside a Spring Boot application. As we
      have a lot of user interaction in our processes, we decided to build a
      suitable tasklist based on [VueJs](https://vuejs.org/) and the beautiful
      [VuetifyJs](https://vuetifyjs.com/) frameworks. The second challenge was
      that we had and have several integrations into our heterogeneous backend
      infrastructure. So we build a thin integration layer of so-called
      "integration artifacts". Last but not least we coded a forms service based
      on JsonSchema and the
      [vjsf](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest)
      library. The Vue Forms component can be plugged in into every VueJs
      application.
    shortDescription: DigiWF project automation platform.
developmentStatus: development
it:
  conforme:
    gdpr: true
    lineeGuidaDesign: false
    misureMinimeSicurezza: false
    modelloInteroperabilita: false
  countryExtensionVersion: '0.2'
  piattaforme:
    anpr: false
    cie: false
    pagopa: false
    spid: false
legal:
  license: MIT
localisation:
  availableLanguages:
    - de
  localisationReady: false
maintenance:
  contacts:
    - email: opensource@muenchendigital.io
      name: it@m
  type: internal
name: DigiWF
platforms:
  - web
releaseDate: '1970-01-01'
softwareType: standalone/other
url: 'https://github.com/it-at-m/digiwf-project'
```

I created an issue for the required `releaseDate` in italia/publiccode-editor#244
